//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int SchoolClassId { get; set; }
        public int StudentId { get; set; }
        public string Grade1 { get; set; }
    
        public virtual SchoolClass SchoolClass { get; set; }
        public virtual Student Student { get; set; }
    }
}
